# Site
repository: rpadam/rpadam.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Raphael Adam
title: Engineering Manager
email: raphaelpauladam@gmail.com
website: raphaelpauladam.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: 
github_username:  rpadam
# stackoverflow_username: 
# dribbble_username: 
# facebook_username: 
# flickr_username: 
# instagram_username: 
linkedin_username: raphaelpauladam
# xing_username: 
# pinterest_username: 
# youtube_username: 
# googleplus_username: 
# orcid_username: 

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/DSC_5185.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is Raphael, and I'm an Engineering leader with 12 years of enterprise software experience and 7 years managing hybrid teams. I'm adept at driving developer productivity, infrastructure tooling, and scalability initiatives. I have a proven ability to lead high-performing teams, align technical strategy with business goals, and optimize engineering processes.
  
  I am most skilled with: <mark>Developer Experiences</mark> and <mark>Change Management</mark>

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Engineering Manager
        # link_text: workiva.com
        sub_title: Workiva
        caption: June 2021 - Present
        quote: >
          TODO: Add quote about Workiva and Engineering Management.
        description: | # this will include new lines to allow paragraphs
            TODO: Add description for role.
      - layout: left
        title: Senior Software Development Engineer in Test, Tech Lead
        # link_text: workiva.com
        sub_title: Workiva
        caption: June 2017 - June 2021
        quote: >
          TODO: Add quote about Role as a Senior SDET.
        description: | # this will include new lines to allow paragraphs
            TODO: Add description for role.
      - layout: left
        title: Software Development Engineer in Test
        # link_text: workiva.com
        sub_title: Workiva
        caption: Jan 2014 - June 2017
        quote: >
          TODO: Add quote about Role as an SDET.
        description: | # this will include new lines to allow paragraphs
            TODO: Add description for role.
      - layout: left
        title: Quality Assurance Analyst Intern
        # link_text: workiva.com
        sub_title: WebFilings
        caption: March 2012 - Jan 2014
        quote: >
          TODO: Add quote about Role as a QA Intern.
        description: | # this will include new lines to allow paragraphs
            TODO: Add description for role.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Iowa State University
        caption: 2009 - 2013
        sub_title: Bachelor of Science in Management Information Systems
        # quote: > 
        description: | # this will include new lines to allow paragraphs
          TODO: Add description

  - title: More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - 3D Printing
      - Electronics and Hardware Tinkering
      - Reading (Sci Fi)

      Look at this cool image  
      ![Trees](/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
