# Site
repository: rpadam/rpadam.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Raphael Adam
title: Engineering Manager
email: raphaelpauladam@gmail.com
website: raphaelpauladam.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: 
github_username:  rpadam
# stackoverflow_username: 
# dribbble_username: 
# facebook_username: 
# flickr_username: 
# instagram_username: 
linkedin_username: raphaelpauladam
# xing_username: 
# pinterest_username: 
# youtube_username: 
# googleplus_username: 
# orcid_username: 

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/IMG_0764.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is Raphael, and I'm an Engineering leader with 12 years of enterprise software experience and 7 years managing hybrid teams. I'm adept at driving developer productivity, infrastructure tooling, and scalability initiatives. I have a proven ability to lead high-performing teams, align technical strategy with business goals, and optimize engineering processes.
  
  I am most skilled with: <mark>Developer Experiences</mark> and <mark>Change Management</mark>

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Engineering Manager
        # link_text: workiva.com
        sub_title: Workiva
        caption: June 2021 - Present
        quote: >
          As an Engineering Manager and leader, I've been lucky to work with many talented engineers. Leading them in their work and careers continues to be something that brings me joy.
        description: | # this will include new lines to allow paragraphs
            As an Engineering Manager, I've lead the Developer Experience, Identity and Access Management, and Public APIs teams. This comes with a diverse set of considerations and technologies that require different types of stakeholder and leadership engagement.
            Workiva is an enterprise software company, where security and customer trust are everything. Identity and Access Management serves a critical role in upholding that customer trust by providing robust authentication and authorization options for every business user's needs.
            Public APIs are a gateway into exciting automation opportunities for customers. Consistency and predictability with Workiva's Public APIs are critical for instilling confidence with customers.
            Developer Experience takes a step back and looks at the internal engineering teams as a customer base. How do we service our engineers needs? How can we operate more efficiently as an R&D organization. It's a fun landscape filled with opportunities and eager stakeholders.
      - layout: left
        title: Senior Software Development Engineer in Test, Tech Lead
        sub_title: Workiva
        caption: June 2017 - June 2021
        quote: >
          Being in a Senior SDET role allowed me to lead teams and more formally mentor other engineers in the engineering organization.
        description: | # this will include new lines to allow paragraphs
            As a Senior SDET, I guided engineers and teams in adopting testing frameworks, while also having opportunities to mentor and manage engineers.
      - layout: left
        title: Software Development Engineer in Test
        sub_title: Workiva
        caption: Jan 2014 - June 2017
        quote: >
          I was in the first batch of engineers to be given the title of SDET as a engineer who has a focus on scalable quality practices in the engineer organization. This formative phase in my career saw me and other SDETs forging what the role would become to this day.
        description: | # this will include new lines to allow paragraphs
            TODO: Add Description.
      - layout: left
        title: Quality Assurance Analyst Intern
        sub_title: WebFilings
        caption: March 2012 - Jan 2014
        quote: >
          Everything about my internship with WebFilings was an amazing and fun introduction. WebFilings was a blossoming startup that maintained a positive work culture where everyone worked and played hard.
        description: | # this will include new lines to allow paragraphs
            As a Quality Assurance Analyst Intern, I was given opportunities on par with that of full time Quality Assurance Analysts. I was entrusted with putting together testing plans for our software suites, writing automated tests, and making sure my teams were able to move quality code with expediancy.
      - layout: left
        title: IT Support and Front Desk
        sub_title: Neurology Specialists LLC
        caption: Jan 2008 - May 2009
        quote: #>
          # TODO: Add quote
        description: | # this will include new lines to allow paragraphs
            As IT Support and Front Desk at Neurology Specialists LLC, my responsibilies ranged from handling sensative patient information and scheduling, to addressing computer issues around the office.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Iowa State University
        caption: 2009 - 2013
        sub_title: Bachelor of Science in Management Information Systems
        # quote: > 
        description: | # this will include new lines to allow paragraphs
          TODO: Add description

  - title: More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      While a lot of my passions involve software and people, I have other interests and hobbies that I enjoy:
      - 3D Printing - Fun for tinkerers, 
      - Electronics and Hardware Tinkering - Think Raspberry Pis and Arduinos
      - Reading - Mostly Science Fiction these days
      - Domestic and International Travel - I let my stomach guide me

      Here I am eating raw pickled herring in Museumplein in Amsterdam.

      ![Amsterdam](\images\IMG_7815.jpeg "Amsterdam"){: width="350" }


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
